# Generated by Django 6.0.3 on 2026-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField(default=100, help_text='Quantity in grams')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=15)),
                ('name', models.CharField(default='My Meal', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carbs', 'Carbohydrates'), ('fat', 'Healthy Fats'), ('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('dairy', 'Dairy'), ('grain', 'Grains'), ('snack', 'Snacks'), ('beverage', 'Beverages')], default='protein', max_length=20)),
                ('calories', models.FloatField(help_text='Calories per 100g')),
                ('protein', models.FloatField(help_text='Protein grams per 100g')),
                ('carbs', models.FloatField(help_text='Carbohydrate grams per 100g')),
                ('fats', models.FloatField(help_text='Fat grams per 100g')),
                ('fiber', models.FloatField(default=0, help_text='Fiber grams per 100g')),
                ('sugar', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0, help_text='Sodium mg per 100g')),
                ('serving_size', models.FloatField(default=100, help_text='Typical serving in grams')),
                ('serving_unit', models.CharField(default='g', max_length=50)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
