# Generated by Django 6.0.3 on 2026-04-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietdetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='diet.dietplan'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category'], name='diet_food_categor_b55c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='diet_food_name_6093af_idx'),
        ),
        migrations.AddField(
            model_name='dietdetail',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.food'),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['user', 'date'], name='diet_dietpl_user_id_e90188_idx'),
        ),
        migrations.AddIndex(
            model_name='dietdetail',
            index=models.Index(fields=['plan'], name='diet_dietde_plan_id_46bc69_idx'),
        ),
    ]
