# Generated by Django 6.0.3 on 2026-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('body_fat', models.FloatField(blank=True, help_text='Body fat percentage', null=True)),
                ('chest', models.FloatField(blank=True, help_text='Chest measurement cm', null=True)),
                ('waist', models.FloatField(blank=True, help_text='Waist measurement cm', null=True)),
                ('hips', models.FloatField(blank=True, help_text='Hips measurement cm', null=True)),
                ('bicep', models.FloatField(blank=True, help_text='Bicep measurement cm', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('energy_level', models.IntegerField(default=5, help_text='1-10 scale')),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
