# Generated by Django 6.0.3 on 2026-04-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'date'], name='progress_pr_user_id_5376c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'date')},
        ),
    ]
