# Generated by Django 6.0.3 on 2026-04-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('abs', 'Abs/Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=15)),
                ('equipment', models.CharField(blank=True, default='', max_length=200)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('calories_per_rep', models.FloatField(default=0.5, help_text='Approx calories per rep')),
                ('is_cardio', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='For cardio exercises', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
                'indexes': [models.Index(fields=['muscle_group'], name='workouts_ex_muscle__443f00_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Workout Plan', max_length=200)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.PositiveIntegerField(default=10)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight used in kg', null=True)),
                ('rest_seconds', models.PositiveIntegerField(default=60, help_text='Rest between sets')),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', 'day'], name='workouts_wo_user_id_a16d55_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutdetail',
            index=models.Index(fields=['plan'], name='workouts_wo_plan_id_ef33a9_idx'),
        ),
    ]
